//data for card Values

export const cardValues = [
    {
        cardTitle:"FREE",
        cardPrice:"0",
        user:"Single",
        storage:"5GB",
        unlimitedPublicProjects:true,
        communityAccess:true,
        unlimitedPrivateProjects:false,
        dedicatedPhoneSupport:false,
        freeSubdomain:false,
        monthlyStatusReport:false
    },
    {
        cardTitle:"PLUS",
        cardPrice:"9",
        user:"5",
        storage:"50GB",
        unlimitedPublicProjects:true,
        communityAccess:true,
        unlimitedPrivateProjects:true,
        dedicatedPhoneSupport:true,
        freeSubdomain:true,
        monthlyStatusReport:false
    },
    {
        cardTitle:"PRO",
        cardPrice:"49",
        user:"Unlimited",
        storage:"150GB",
        unlimitedPublicProjects:true,
        communityAccess:true,
        unlimitedPrivateProjects:true,
        dedicatedPhoneSupport:true,
        freeSubdomain:true,
        monthlyStatusReport:true
    }
];
